feat: add `npm_config_user_agent` support
antfu-collective/package-manager-detector pull request #20
Opened 2024-10-14 17:03 UTC by userquin

### Description

### Linked Issues

resolves # #19

### Additional context

2024-10-14 18:09 UTC, userquin commented
Why breaking? The default flag is undefined and will not check for the env entry

2024-10-14 18:51 UTC, userquin commented on src/types.ts
> +  npm_config_user_agent?: true | 'continue'
Use true only

2024-10-14 19:05 UTC, benmccann commented
Thanks for the update! Yeah, not a breaking change

Though I do think separate methods would be better for tree shaking. Right now we basically have `if (opt) { method1() } else { method2() }`. Why not just let the user call the method they need directly to avoid including code for the method they don't need?

2024-10-14 19:17 UTC, benmccann commented on src/detect.ts
> +function processUserAgent(pm: any, onUnknown: DetectOptions['onUnknown']): DetectResult | null {
we should probably add some tests for this

here's an implementation from another project I've worked on:
```
export function getUserAgent(): AgentName | undefined {
	const userAgent = process.env.npm_config_user_agent;
	if (!userAgent) return undefined;

	const pmSpec = userAgent.split(' ')[0]!;
	const separatorPos = pmSpec.lastIndexOf('/');
	const name = pmSpec.substring(0, separatorPos) as AgentName;
	return AGENTS.includes(name) ? name : undefined;
}
```

i'm surprised the two implementations are so different, but haven't looked into the differences or if one is handling some cases differently

2024-10-14 22:00 UTC, MichaelDeBoey commented
Now that I created https://github.com/antfu-collective/package-manager-detector/issues/21, I'm not sure if using `npm_config_user_agent` would (always) be the correct thing to look at though 🤔

2024-10-15 15:19 UTC, benmccann approved these changes
nice!!

Thanks @userquin !

2024-10-15 15:22 UTC, benmccann commented
> Now that I created https://github.com/antfu-collective/package-manager-detector/issues/21, I'm not sure if using npm_config_user_agent would (always) be the correct thing to look at though 🤔

We can add support for Deno in this method when implementing https://github.com/antfu-collective/package-manager-detector/issues/21. I'll comment there with some more details. I don't think it should block this PR though

2024-10-15 16:20 UTC, MichaelDeBoey requested changes

2024-10-15 16:20 UTC, MichaelDeBoey commented on src/detect.ts
> +    return null
This makes it a bit more readable for less experienced people

```suggestion
  if (!userAgent) {
    return null
  }
```

2024-10-15 16:20 UTC, MichaelDeBoey commented on src/detect.ts
> +  const name = userAgent.split(' ')[0].split('/')[0] as AgentName
I don't think we first need to split on empty space (`' '`) and we can just split on `/` directly, just like we do in the Remix codebase?
https://github.com/remix-run/remix/blob/8649f1a561ce5ea0bfba5ab862c0c94052f4a5c3/packages/remix-dev/cli/detectPackageManager.ts#L10-L23

```suggestion
  const name = userAgent.split('/')[0] as AgentName
```

2024-10-15 16:20 UTC, MichaelDeBoey commented on test/user-agent.spec.ts
> +    ['pnpm', 'pnpm/9.12.1 npm/? node/v20.17.0 linux x64'],
Maybe we should add a test for bun as well?

2024-10-15 16:45 UTC, benmccann commented on test/user-agent.spec.ts
> +    ['pnpm', 'pnpm/9.12.1 npm/? node/v20.17.0 linux x64'],
```suggestion
    ['pnpm', 'pnpm/9.12.1 npm/? node/v20.17.0 linux x64'],
    ['bun', 'bun/1.1.8 npm/? node/v21.6.0 linux x64'],
```

2024-10-15 16:52 UTC, MichaelDeBoey approved these changes

2024-10-15 20:06 UTC, antfu approved these changes

2024-10-15 20:39 UTC, merged