feat: add `types` subpackage export
antfu-collective/package-manager-detector pull request #27
Opened 2024-11-15 21:12 UTC by userquin

### Description

This PR adds the types moduke to the unbuild command and the entries to the package.json.

### Linked Issues
resolves #26

### Additional context

2024-11-15 21:13 UTC, userquin commented on build.config.ts
> +export default defineBuildConfig([{
rmeove the array

2024-11-15 21:25 UTC, benmccann commented
I'm not much of a Typescript expert, but is this the right thing to do? I can't remember using any other packages where you import types from a separate subpath and am not even sure how that would work.

If I understand correctly what they want to do is `import { resolveCommand } from 'package-manager-detector/commands'`. But how would you import it both from there and from `'package-manager-detector/commands'`?

I think the issue might be that there is no `types` field under `commands` in the `package.json`

2024-11-15 21:34 UTC, userquin commented
I guess it shouldn't use the default package to import `resolveCommand`, this code:
```
import {
	resolveCommand,
	type Agent,
	type Command,
	type ResolvedCommand,
} from "package-manager-detector";
```

should be:
```ts
import type { Agent Command, ResolvedCommand } from "package-manager-detector";
import { resolveCommand } from "package-manager-detector/commands";
```

2024-11-16 06:53 UTC, antfu approved these changes

2024-11-16 14:04 UTC, benmccann requested changes
I think we can close this per @userquin's last comment

2024-11-16 14:54 UTC, closed without merging

2024-11-16 14:55 UTC, antfu commented
Either way would work for me (I often expose `/types` for quite a few packages), but yeah, to the original issue is more like a usage issue